public enum EventID
{
    PLAYER_DEATH,
    PLAYER_SHOOTING,
    PLAYER_THROWING_GRENADE,
    PLAY_GAME,
    UPDATING_WEAPON_INVENTORY,
    SWITCHING_WEAPON,
    CHANGING_COIN_QUANTITY,
    GAME_OVER,
    ENEMY_DEATH,
    PLAYFAB_LOGGINGIN
}